namespace('PAINT.SELECTION').DEFAULT_SELECTION = 'PEN_TOOL';
namespace('PAINT').DEFAULTS = {
    STATUS: false,
    STROKE_COLOR: '#000 ',
    LINE_WIDTH:5,
    CURRENT_SELECTION:"PAINT_TOOL"
};
namespace('PAINT').COMPONENTS = {
    PEN: 'PEN_TOOL',
    ERASER: 'ERASER_TOOL',
    RECTANGLE:'RECTANGLE_TOOL',
    COLORPICKER:'COLORPICKER_TOOL'
};
PAINT.SELECTION.DEFAULT_STROKE_COLOR='#000'
PAINT.SELECTION.CURRENT_SELECTION=PAINT.SELECTION.DEFAULT_SELECTION;
PAINT.SELECTION.CURRENT_STROKE=PAINT.DEFAULTS.STROKE_COLOR
PAINT.SELECTION.CURRENT_LINE_WIDTH=PAINT.DEFAULTS.LINE_WIDTH
PAINT.SELECTION.POINT={
    X:'',
    Y:'',
    PAINT:PAINT.DEFAULTS.STATUS,
    STROKE_COLOR:PAINT.SELECTION.CURRENT_STROKE,
    LINE_WIDTH:PAINT.SELECTION.CURRENT_LINE_WIDTH,
    SELECTION:PAINT.SELECTION.CURRENT_SELECTION
};
PAINT.SELECTION.IS_MOUSE_DOWN=false;
PAINT.SELECTION.SELECTION_MODEL={
    POINTS:[],
    UNDO:[],
    REDO:[]
};